ALTER TABLE banks MODIFY COLUMN code varchar(50) NOT NULL;
ALTER TABLE banks ADD COLUMN is_active bool;

INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Central Asia','BCA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Mandiri','MANDIRI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Negara Indonesia','BNI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Permata','PERMATA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Rakyat Indonesia','BRI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('CIMB Niaga Bank','CIMB_NIAGA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Danamon','DANAMON', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Panin','PANIN', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Maybank','BII', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Anglomas International Bank','ANGLOMAS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bangkok Bank','BANGKOK', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Agris','AGRIS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Sinarmas','SINARMAS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Agroniaga','AGRONIAGA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Andara','ANDARA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Antar Daerah','ANTAR_DAERAH', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank ANZ Indonesia','ANZ', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Artha Graha International','ARTHA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Artos Indonesia','ARTOS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Bisnis Internasional','BISNIS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank BJB','BJB', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank BNP Paribas','BNP', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Bukopin','BUKOPIN', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Bumi Arta','BUMI_ARTA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Capital Indonesia','CAPITAL', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Central Asia (BCA) Syariah','BCA_SYR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Chinatrust Indonesia','CHINATRUST', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank CIMB Niaga UUS','CIMB_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Commonwealth','COMMONWEALTH', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Danamon UUS','DANAMON_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank DBS Indonesia','DBS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Dinar Indonesia','DINAR_INDONESIA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank DKI','DKI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank DKI UUS','DKI_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Ekonomi Raharja','EKONOMI_RAHARJA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Fama International','FAMA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Ganesha','GANESHA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Hana','HANA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Harda Internasional','HARDA_INTERNASIONAL', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Himpunan Saudara 1906','HIMPUNAN_SAUDARA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank ICBC Indonesia','ICBC', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Ina Perdana','INA_PERDANA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Index Selindo','INDEX_SELINDO', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Jasa Jakarta','JASA_JAKARTA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Kesejahteraan Ekonomi','KESEJAHTERAAN_EKONOMI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Maspion Indonesia','MASPION', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Mayapada International','MAYAPADA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Maybank Syariah Indonesia','MAYBANK_SYR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Mayora','MAYORA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Mega','MEGA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Mestika Dharma','MESTIKA_DHARMA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Metro Express','METRO_EXPRESS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Mizuho Indonesia','MIZUHO', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank MNC Internasional','MNC_INTERNASIONAL', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Muamalat Indonesia','MUAMALAT', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Multi Arta Sentosa','MULTI_ARTA_SENTOSA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Mutiara','MUTIARA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Nationalnobu','NATIONALNOBU', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Nusantara Parahyangan','NUSANTARA_PARAHYANGAN', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank OCBC NISP','OCBC', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank OCBC NISP UUS','OCBC_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank of America Merill-Lynch','BAML', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank of China (BOC)','BOC', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank of India Indonesia','INDIA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank of Tokyo Mitsubishi UFJ','TOKYO', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Panin Syariah','PANIN_SYR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Permata UUS','PERMATA_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Pundi Indonesia','PUNDI_INDONESIA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank QNB Kesawan','QNB_KESAWAN', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Rabobank International Indonesia','RABOBANK', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Resona Perdania','RESONA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Royal Indonesia','ROYAL', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Sahabat Purba Danarta','SAHABAT_PURBA_DANARTA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Sahabat Sampoerna','SAHABAT_SAMPOERNA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank SBI Indonesia','SBI_INDONESIA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Sinar Harapan Bali','SINAR_HARAPAN_BALI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Sumitomo Mitsui Indonesia','MITSUI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Syariah BRI','BRI_SYR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Syariah Bukopin','BUKOPIN_SYR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Syariah Mandiri','MANDIRI_SYR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Syariah Mega','MEGA_SYR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Tabungan Negara (BTN)','BTN', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Tabungan Negara (BTN) UUS','BTN_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Tabungan Pensiunan Nasional','TABUNGAN_PENSIUNAN_NASIONAL', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Tabungan Pensiunan Nasional UUS','TABUNGAN_PENSIUNAN_NASIONAL_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank UOB Indonesia','UOB', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Victoria Internasional','VICTORIA_INTERNASIONAL', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Victoria Syariah','VICTORIA_SYR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Windu Kentjana Int','WINDU', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Woori Indonesia','WOORI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Yudha Bhakti','YUDHA_BHAKTI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Aceh','ACEH', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Aceh UUS','ACEH_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Bali','BALI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Bengkulu','BENGKULU', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Pembangunan Daerah (BPD DIY)','BPD_DIY', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Pembangunan Daerah (BPD DIY) Syariah','BPD_DIY_SYR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Jambi','JAMBI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Jambi UUS','JAMBI_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Jawa Tengah','JAWA_TENGAH', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Jawa Tengah UUS','JAWA_TENGAH_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Jawa Timur','JAWA_TIMUR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Jawa Timur UUS','JAWA_TIMUR_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Kalimantan Barat','KALIMANTAN_BARAT', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Kalimantan Barat UUS','KALIMANTAN_BARAT_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Kalimantan Selatan','KALIMANTAN_SELATAN', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Kalimantan Selatan UUS','KALIMANTAN_SELATAN_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Kalimantan Tengah','KALIMANTAN_TENGAH', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Kalimantan Timur','KALIMANTAN_TIMUR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Kalimantan Timur UUS','KALIMANTAN_TIMUR_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Lampung','LAMPUNG', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Maluku','MALUKU', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Nusa Tenggara Barat','NUSA_TENGGARA_BARAT', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Nusa Tenggara Barat UUS','NUSA_TENGGARA_BARAT_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Nusa Tenggara Timur','NUSA_TENGGARA_TIMUR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Papua','PAPUA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Riau Dan Kepri','RIAU_DAN_KEPRI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Riau Dan Kepri UUS','RIAU_DAN_KEPRI_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Sulawesi Tengah','SULAWESI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Sulawesi Tenggara','SULAWESI_TENGGARA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Sulselbar','SULSELBAR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Sulselbar UUS','SULSELBAR_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Sulut','SULUT', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Sumatera Barat','SUMATERA_BARAT', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Sumatera Barat UUS','SUMATERA_BARAT_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Sumsel Dan Babel','SUMSEL_DAN_BABEL', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Sumsel Dan Babel UUS','SUMSEL_DAN_BABEL_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Sumut','SUMUT', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Sumut UUS','SUMUT_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Centratama Nasional Bank','CENTRATAMA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Citibank','CITIBANK', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Deutsche Bank','DEUTSCHE', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Hongkong and Shanghai Bank Corporation (HSBC)','HSBC', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Hongkong and Shanghai Bank Corporation (HSBC) UUS','HSBC_UUS', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('JP Morgan Chase Bank','JPMORGAN', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Prima Master Bank','PRIMA_MASTER', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Standard Charted Bank','STANDARD_CHARTERED', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Mitra Niaga','MITRA_NIAGA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Ekspor Indonesia','EKSPOR_INDONESIA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Arta Niaga Kencana','ARTA_NIAGA_KENCANA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank BJB Syariah','BJB_SYR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank BNI Syariah','BNI_SYR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BSI (Bank Syariah Indonesia)','BSI', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Blu/BCA Digital','BCA_DIGITAL', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank IBK Indonesia','IBK', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPD Banten','BANTEN', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank China Construction Bank Indonesia','CCB', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BPR EKA (Bank Eka)','EKA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('BANK MANTAP (Mandiri Taspen)','MANTAP', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank Shinhan Indonesia','SHINHAN', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('GoPay','GOPAY', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('OVO','OVO', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('ShopeePay','SHOPEEPAY', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Dana','DANA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('LinkAja','LINKAJA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Sinarmas Syariah','SINARMAS_SYR', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Bank KEB HANA','KEB_HANA', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Al','BankALLO', true);
INSERT INTO banks(bank_name,code,is_active) VALUES ('Kustodian Sentral Ef','IndonesiaKSEI', true);